### ISSUE TITLE
0.9 Milestone

### ISSUE THREAD

**Issue by micnic** [micnic/simpleS#8]
**Leave node.js 0.10, 0.12 and io.js 1.x - 3.x support**
- [ ] Partial use of ES6 features
- [ ] Use of newest node API

**Add multi cluster support**
- [ ] Add workers
- [ ] Remove `domains` module usage

**Change template engine API**
- [ ] Add support for Express-like API for template engines
- [ ] Update simpleT

**0.8.x changes (can be delayed for 0.9.0)**
- [ ] Add support for virtual hosts defined with wild cards
- [ ] Add support for FormData in simpleS client API

*This list is updated*
